version: '3'

services:
        web:
            image: '24daemon/nodejsapp'
            ports:
                    - "3000:3000"
            volumes:
                    - /app/node_modules
                    - .:/app

                      #            command: ["npm", "run", "test"]
